name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build app
        run: ./buildprod.sh

      - name: Build Docker
        run: docker build -t lanecwagner/notely:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: lanecwagner
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push to Docker Hub
        run: docker push lanecwagner/notely:latest
